// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsRCkSmMIiC5dvREFY7Q4KZ-Lr4zaK-ns',
    appId: '1:684767557115:web:bfc70c5339ec56da62475e',
    messagingSenderId: '684767557115',
    projectId: 'vet-sphere-app',
    authDomain: 'vet-sphere-app.firebaseapp.com',
    storageBucket: 'vet-sphere-app.firebasestorage.app',
    measurementId: 'G-HJE5E3NJG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2GQRW8XcSKLIUS-c5OkoUvCCo9IC6fbk',
    appId: '1:684767557115:android:fe6630054a99cc0162475e',
    messagingSenderId: '684767557115',
    projectId: 'vet-sphere-app',
    storageBucket: 'vet-sphere-app.firebasestorage.app',
  );
}
